### ISSUE TITLE
Build fails after c95b33500c49836f0f1b277c226d5f136beaf179

### ISSUE THREAD

**Issue by h0nzZik** [kframework/c-semantics#272]
After c95b33500c49836f0f1b277c226d5f136beaf179, I am not able to build the semantics. However, building with 2ecd8fe2e5c755313a5b4da109821effc1632234 and 46628b282e3cd70d67906d41c565ce3393668de2 without c95b33500c49836f0f1b277c226d5f136beaf179 works fine.

However, log does not seem to contain anything interesting:

```
kdep -d "x86-gcc-limited-libc/c11-nd-thread-kompiled" -I /path/to/c-semantics/x86-gcc-limited-libc/semantics -I /path/to/c-semantics/x86-gcc-limited-libc/cpp-semantics -- c11-cpp14.k > .depend-nd-thread-tmp
mv .depend-nd-thread-tmp .depend-nd-thread
kdep -d "x86-gcc-limited-libc/c11-nd-kompiled" -I /path/to/c-semantics/x86-gcc-limited-libc/semantics -I /path/to/c-semantics/x86-gcc-limited-libc/cpp-semantics -- c11-cpp14.k > .depend-nd-tmp
mv .depend-nd-tmp .depend-nd
kdep  -d "x86-gcc-limited-libc/c11-cpp14-kompiled" -I /path/to/c-semantics/x86-gcc-limited-libc/semantics -I /path/to/c-semantics/x86-gcc-limited-libc/cpp-semantics -- c11-cpp14.k > .depend-execution-tmp
mv .depend-execution-tmp .depend-execution
kdep  -d "x86-gcc-limited-libc/cpp14-translation-kompiled" -I /path/to/c-semantics/x86-gcc-limited-libc/cpp-semantics -I /path/to/c-semantics/x86-gcc-limited-libc/semantics -- cpp14/cpp14-translation.k > .depend-cpp-tmp
mv .depend-cpp-tmp .depend-cpp
kdep  -d "x86-gcc-limited-libc/c11-translation-kompiled" -I /path/to/c-semantics/x86-gcc-limited-libc/semantics -- c11/c11-translation.k > .depend-translation-tmp
mv .depend-translation-tmp .depend-translation
Kompiling the static C++ semantics...
kompile -O2 --backend ocaml --non-strict --exit-code "<result-value> _:Int </result-value>" -w2e --opaque-klabels c11/c11-translation.k --smt none cpp14/cpp14-translation.k -d "x86-gcc-limited-libc/cpp14-translation-kompiled" --no-prelude -w all -v --debug -I /path/to/c-semantics/x86-gcc-limited-libc/cpp-semantics -I /path/to/c-semantics/x86-gcc-limited-libc/semantics
Parse command line options                                   =    49
Importing: Source(/path/to/c-semantics/semantics/./cpp14/cpp14-translation.k)
Importing: Source(/path/to//runtimeverification/k/k-distribution/target/release/k/include/builtin/kast.k)
Importing: Source(/path/to//runtimeverification/k/k-distribution/target/release/k/include/builtin/domains.k)
Importing: Source(/path/to/c-semantics/semantics/cpp14/language/translation/translation.k)
Importing: Source(/path/to/c-semantics/semantics/cpp14/language/translation/conversion.k)
Importing: Source(/path/to/c-semantics/semantics/cpp14/language/translation/elaborator.k)
Importing: Source(/path/to/c-semantics/semantics/cpp14/language/translation/env.k)
Importing: Source(/path/to/c-semantics/semantics/cpp14/language/translation/error.k)
Importing: Source(/path/to/c-semantics/semantics/cpp14/language/translation/init.k)
Importing: Source(/path/to/c-semantics/semantics/cpp14/language/translation/io.k)
Importing: Source(/path/to/c-semantics/semantics/cpp14/language/translation/name.k)
Importing: Source(/path/to/c-semantics/semantics/cpp14/language/translation/operators.k)
Importing: Source(/path/to/c-semantics/semantics/cpp14/language/translation/overloading.k)
Importing: Source(/path/to/c-semantics/semantics/cpp14/language/translation/process-label.k)
Importing: Source(/path/to/c-semantics/semantics/cpp14/language/translation/promotion.k)
Importing: Source(/path/to/c-semantics/semantics/cpp14/language/translation/syntax.k)
Importing: Source(/path/to/c-semantics/semantics/cpp14/language/translation/template-deduction.k)
Importing: Source(/path/to/c-semantics/semantics/cpp14/language/translation/value-category.k)
Importing: Source(/path/to/c-semantics/semantics/cpp14/language/translation/configuration.k)
Importing: Source(/path/to/c-semantics/semantics/cpp14/language/translation/decl/class.k)
Importing: Source(/path/to/c-semantics/semantics/cpp14/language/translation/decl/declarator.k)
Importing: Source(/path/to/c-semantics/semantics/cpp14/language/translation/decl/enum.k)
Importing: Source(/path/to/c-semantics/semantics/cpp14/language/translation/decl/initializer.k)
Importing: Source(/path/to/c-semantics/semantics/cpp14/language/translation/decl/linkage.k)
Importing: Source(/path/to/c-semantics/semantics/cpp14/language/translation/decl/namespace.k)
Importing: Source(/path/to/c-semantics/semantics/cpp14/language/translation/decl/template.k)
Importing: Source(/path/to/c-semantics/semantics/cpp14/language/translation/decl/typedef.k)
Importing: Source(/path/to/c-semantics/semantics/cpp14/language/translation/expr/additive.k)
Importing: Source(/path/to/c-semantics/semantics/cpp14/language/translation/expr/alignof.k)
Importing: Source(/path/to/c-semantics/semantics/cpp14/language/translation/expr/assignment.k)
Importing: Source(/path/to/c-semantics/semantics/cpp14/language/translation/expr/bitwise.k)
Importing: Source(/path/to/c-semantics/semantics/cpp14/language/translation/expr/cast.k)
Importing: Source(/path/to/c-semantics/semantics/cpp14/language/translation/expr/comma.k)
Importing: Source(/path/to/c-semantics/semantics/cpp14/language/translation/expr/conditional.k)
Importing: Source(/path/to/c-semantics/semantics/cpp14/language/translation/expr/function-call.k)
Importing: Source(/path/to/c-semantics/semantics/cpp14/language/translation/expr/eval.k)
Importing: Source(/path/to/c-semantics/semantics/cpp14/language/translation/expr/inc-and-dec.k)
Importing: Source(/path/to/c-semantics/semantics/cpp14/language/translation/expr/literal.k)
Importing: Source(/path/to/c-semantics/semantics/cpp14/language/translation/expr/logical.k)
Importing: Source(/path/to/c-semantics/semantics/cpp14/language/translation/expr/members.k)
Importing: Source(/path/to/c-semantics/semantics/cpp14/language/translation/expr/multiplicative.k)
Importing: Source(/path/to/c-semantics/semantics/cpp14/language/translation/expr/new.k)
Importing: Source(/path/to/c-semantics/semantics/cpp14/language/translation/expr/reference.k)
Importing: Source(/path/to/c-semantics/semantics/cpp14/language/translation/expr/relational.k)
Importing: Source(/path/to/c-semantics/semantics/cpp14/language/translation/expr/sizeof.k)
Importing: Source(/path/to/c-semantics/semantics/cpp14/language/translation/expr/unary.k)
Importing: Source(/path/to/c-semantics/semantics/cpp14/language/translation/stmt/block.k)
Importing: Source(/path/to/c-semantics/semantics/cpp14/language/translation/stmt/canonicalization.k)
Importing: Source(/path/to/c-semantics/semantics/cpp14/language/translation/stmt/expr.k)
Importing: Source(/path/to/c-semantics/semantics/cpp14/language/translation/stmt/goto.k)
Importing: Source(/path/to/c-semantics/semantics/cpp14/language/translation/stmt/if.k)
Importing: Source(/path/to/c-semantics/semantics/cpp14/language/translation/stmt/labeled.k)
Importing: Source(/path/to/c-semantics/semantics/cpp14/language/translation/stmt/loop.k)
Importing: Source(/path/to/c-semantics/semantics/cpp14/language/translation/stmt/return.k)
Importing: Source(/path/to/c-semantics/semantics/cpp14/language/translation/stmt/try.k)
Importing: Source(/path/to/c-semantics/semantics/cpp14/language/translation/typing/canonicalization.k)
Importing: Source(/path/to/c-semantics/semantics/cpp14/language/translation/typing/dependent.k)
Importing: Source(/path/to/c-semantics/semantics/cpp14/language/translation/typing/expr.k)
Importing: Source(/path/to/c-semantics/x86-gcc-limited-libc/cpp-semantics/cpp-extensions-translation.k)
Importing: Source(/path/to/c-semantics/semantics/cpp14/language/common/common.k)
Importing: Source(/path/to/c-semantics/semantics/cpp14/language/common/alignment.k)
Importing: Source(/path/to/c-semantics/semantics/cpp14/language/common/bitsize.k)
Importing: Source(/path/to/c-semantics/semantics/cpp14/language/common/builtin.k)
Importing: Source(/path/to/c-semantics/semantics/cpp14/language/common/class.k)
Importing: Source(/path/to/c-semantics/semantics/cpp14/language/common/conversion.k)
Importing: Source(/path/to/c-semantics/semantics/cpp14/language/common/dynamic.k)
Importing: Source(/path/to/c-semantics/semantics/cpp14/language/common/error.k)
Importing: Source(/path/to/c-semantics/semantics/cpp14/language/common/promotion-context.k)
Importing: Source(/path/to/c-semantics/semantics/cpp14/language/common/reference.k)
Importing: Source(/path/to/c-semantics/semantics/cpp14/language/common/settings.k)
Importing: Source(/path/to/c-semantics/semantics/cpp14/language/common/symloc.k)
Importing: Source(/path/to/c-semantics/semantics/cpp14/language/common/syntax.k)
Importing: Source(/path/to/c-semantics/semantics/cpp14/language/common/typing.k)
Importing: Source(/path/to/c-semantics/semantics/cpp14/language/common/expr/additive.k)
Importing: Source(/path/to/c-semantics/semantics/cpp14/language/common/expr/bitwise.k)
Importing: Source(/path/to/c-semantics/semantics/cpp14/language/common/expr/cast.k)
Importing: Source(/path/to/c-semantics/semantics/cpp14/language/common/expr/eval.k)
Importing: Source(/path/to/c-semantics/semantics/cpp14/language/common/expr/multiplicative.k)
Importing: Source(/path/to/c-semantics/semantics/cpp14/language/common/expr/members.k)
Importing: Source(/path/to/c-semantics/semantics/cpp14/language/common/expr/relational.k)
Importing: Source(/path/to/c-semantics/semantics/cpp14/language/common/expr/unary.k)
Importing: Source(/path/to/c-semantics/semantics/cpp14/language/common/memory/alloc.k)
Importing: Source(/path/to/c-semantics/semantics/cpp14/language/common/memory/reading.k)
Importing: Source(/path/to/c-semantics/semantics/cpp14/language/common/memory/writing.k)
Importing: Source(/path/to/c-semantics/semantics/cpp14/language/common/stmt/expr.k)
Importing: Source(/path/to/c-semantics/x86-gcc-limited-libc/cpp-semantics/cpp-extensions-common.k)
Importing: Source(/path/to/c-semantics/semantics/linking/linking.k)
Importing: Source(/path/to/c-semantics/semantics/common/common.k)
Importing: Source(/path/to/c-semantics/semantics/common/alignment.k)
Importing: Source(/path/to/c-semantics/semantics/common/bits.k)
Importing: Source(/path/to/c-semantics/semantics/common/builtin.k)
Importing: Source(/path/to/c-semantics/semantics/common/compat.k)
Importing: Source(/path/to/c-semantics/semantics/common/configuration.k)
Importing: Source(/path/to/c-semantics/semantics/common/error.k)
Importing: Source(/path/to/c-semantics/semantics/common/init.k)
Importing: Source(/path/to/c-semantics/semantics/common/memory.k)
Importing: Source(/path/to/c-semantics/semantics/common/resolution.k)
Importing: Source(/path/to/c-semantics/semantics/common/settings.k)
Importing: Source(/path/to/c-semantics/semantics/common/symloc.k)
Importing: Source(/path/to/c-semantics/semantics/common/syntax.k)
Importing: Source(/path/to/c-semantics/semantics/linking/error.k)
Importing: Source(/path/to/c-semantics/semantics/linking/init.k)
Importing: Source(/path/to/c-semantics/semantics/linking/resolution.k)
Importing: Source(/path/to/c-semantics/semantics/c11/language/common/alignment.k)
Importing: Source(/path/to/c-semantics/semantics/c11/language/common/promotion.k)
Importing: Source(/path/to/c-semantics/semantics/c11/language/common/typing/common.k)
Importing: Source(/path/to/c-semantics/semantics/c11/language/common/typing/compatibility.k)
Importing: Source(/path/to/c-semantics/semantics/c11/language/common/typing.k)
Importing: Source(/path/to/c-semantics/semantics/c11/language/common/settings.k)
Importing: Source(/path/to/c-semantics/x86-gcc-limited-libc/semantics/c-settings.k)
Importing: Source(/path/to/c-semantics/semantics/cpp14/language/linking/resolution.k)
Importing: Source(/path/to/c-semantics/x86-gcc-limited-libc/cpp-semantics/cpp-settings.k)
/tmp/tmp-kompile-3920466660543057499.l:2451: warning, rule cannot be matched
/tmp/tmp-kompile-433125670004862106.l:18225: warning, rule cannot be matched
/tmp/tmp-kompile-7121154872073150187.l:48464: warning, rule cannot be matched
Parse definition [3121/3146 rules]                           = 133776
Apply compile pipeline                                       = 12911
/tmp/tmp-kompile-726289431847268140.l:58177: warning, rule cannot be matched
/tmp/tmp-kompile-8999958745240912615.l:58177: warning, rule cannot be matched
Importing: Source(/path/to/c-semantics/semantics/./c11/c11-translation.k)
Importing: Source(/path/to/c-semantics/semantics/c11/c11-translation.k)
Importing: Source(/path/to//runtimeverification/k/k-distribution/target/release/k/include/builtin/kast.k)
Importing: Source(/path/to//runtimeverification/k/k-distribution/target/release/k/include/builtin/domains.k)
Importing: Source(/path/to/c-semantics/semantics/c11/language/translation/translation.k)
Importing: Source(/path/to/c-semantics/semantics/c11/language/translation/syntax.k)
Importing: Source(/path/to/c-semantics/semantics/c11/language/translation/annotation.k)
Importing: Source(/path/to/c-semantics/semantics/c11/language/translation/compound-literal.k)
Importing: Source(/path/to/c-semantics/semantics/c11/language/translation/configuration.k)
Importing: Source(/path/to/c-semantics/semantics/c11/language/translation/elaborator.k)
Importing: Source(/path/to/c-semantics/semantics/c11/language/translation/env.k)
Importing: Source(/path/to/c-semantics/semantics/c11/language/translation/error.k)
Importing: Source(/path/to/c-semantics/semantics/c11/language/translation/function-def.k)
Importing: Source(/path/to/c-semantics/semantics/c11/language/translation/init.k)
Importing: Source(/path/to/c-semantics/semantics/c11/language/translation/io-direct.k)
Importing: Source(/path/to/c-semantics/semantics/c11/language/translation/literal.k)
Importing: Source(/path/to/c-semantics/semantics/c11/language/translation/process-label.k)
Importing: Source(/path/to/c-semantics/semantics/c11/language/translation/promotion.k)
Importing: Source(/path/to/c-semantics/semantics/c11/language/translation/decl/definition.k)
Importing: Source(/path/to/c-semantics/semantics/c11/language/translation/decl/global.k)
Importing: Source(/path/to/c-semantics/semantics/c11/language/translation/decl/initializer.k)
Importing: Source(/path/to/c-semantics/semantics/c11/language/translation/decl/local.k)
Importing: Source(/path/to/c-semantics/semantics/c11/language/translation/decl/resolution.k)
Importing: Source(/path/to/c-semantics/semantics/c11/language/translation/decl/tagged.k)
Importing: Source(/path/to/c-semantics/semantics/c11/language/translation/decl/typedef.k)
Importing: Source(/path/to/c-semantics/semantics/c11/language/translation/expr/additive.k)
Importing: Source(/path/to/c-semantics/semantics/c11/language/translation/expr/alignof.k)
Importing: Source(/path/to/c-semantics/semantics/c11/language/translation/expr/assignment.k)
Importing: Source(/path/to/c-semantics/semantics/c11/language/translation/expr/bitwise.k)
Importing: Source(/path/to/c-semantics/semantics/c11/language/translation/expr/cast.k)
Importing: Source(/path/to/c-semantics/semantics/c11/language/translation/expr/conditional.k)
Importing: Source(/path/to/c-semantics/semantics/c11/language/translation/expr/eval.k)
Importing: Source(/path/to/c-semantics/semantics/c11/language/translation/expr/function-call.k)
Importing: Source(/path/to/c-semantics/semantics/c11/language/translation/expr/identifier.k)
Importing: Source(/path/to/c-semantics/semantics/c11/language/translation/expr/inc-and-dec.k)
Importing: Source(/path/to/c-semantics/semantics/c11/language/translation/expr/logical.k)
Importing: Source(/path/to/c-semantics/semantics/c11/language/translation/expr/members.k)
Importing: Source(/path/to/c-semantics/semantics/c11/language/translation/expr/multiplicative.k)
Importing: Source(/path/to/c-semantics/semantics/c11/language/translation/expr/offsetof.k)
Importing: Source(/path/to/c-semantics/semantics/c11/language/translation/expr/reference.k)
Importing: Source(/path/to/c-semantics/semantics/c11/language/translation/expr/relational.k)
Importing: Source(/path/to/c-semantics/semantics/c11/language/translation/expr/sequencing.k)
Importing: Source(/path/to/c-semantics/semantics/c11/language/translation/expr/sizeof.k)
Importing: Source(/path/to/c-semantics/semantics/c11/language/translation/expr/unary.k)
Importing: Source(/path/to/c-semantics/semantics/c11/language/translation/stmt/block.k)
Importing: Source(/path/to/c-semantics/semantics/c11/language/translation/stmt/break.k)
Importing: Source(/path/to/c-semantics/semantics/c11/language/translation/stmt/goto.k)
Importing: Source(/path/to/c-semantics/semantics/c11/language/translation/stmt/if-then.k)
Importing: Source(/path/to/c-semantics/semantics/c11/language/translation/stmt/labeled.k)
Importing: Source(/path/to/c-semantics/semantics/c11/language/translation/stmt/loop.k)
Importing: Source(/path/to/c-semantics/semantics/c11/language/translation/stmt/return.k)
Importing: Source(/path/to/c-semantics/semantics/c11/language/translation/stmt/static-assert.k)
Importing: Source(/path/to/c-semantics/semantics/c11/language/translation/stmt/switch.k)
Importing: Source(/path/to/c-semantics/semantics/c11/language/translation/typing/canonicalization.k)
Importing: Source(/path/to/c-semantics/semantics/c11/language/translation/typing/interpretation.k)
Importing: Source(/path/to/c-semantics/semantics/c11/language/translation/typing/expr.k)
Importing: Source(/path/to/c-semantics/x86-gcc-limited-libc/semantics/c-extensions-translation.k)
Importing: Source(/path/to/c-semantics/semantics/c11/language/common/common.k)
Importing: Source(/path/to/c-semantics/semantics/c11/language/common/alignment.k)
Importing: Source(/path/to/c-semantics/semantics/c11/language/common/binding.k)
Importing: Source(/path/to/c-semantics/semantics/c11/language/common/bitsize.k)
Importing: Source(/path/to/c-semantics/semantics/c11/language/common/bits.k)
Importing: Source(/path/to/c-semantics/semantics/c11/language/common/conversion.k)
Importing: Source(/path/to/c-semantics/semantics/c11/language/common/dynamic.k)
Importing: Source(/path/to/c-semantics/semantics/c11/language/common/error.k)
Importing: Source(/path/to/c-semantics/semantics/c11/language/common/os-settings.k)
Importing: Source(/path/to/c-semantics/semantics/c11/language/common/promotion-context.k)
Importing: Source(/path/to/c-semantics/semantics/c11/language/common/promotion.k)
Importing: Source(/path/to/c-semantics/semantics/c11/language/common/settings.k)
Importing: Source(/path/to/c-semantics/semantics/c11/language/common/symloc.k)
Importing: Source(/path/to/c-semantics/semantics/c11/language/common/syntax.k)
Importing: Source(/path/to/c-semantics/semantics/c11/language/common/type-builder.k)
Importing: Source(/path/to/c-semantics/semantics/c11/language/common/typing.k)
Importing: Source(/path/to/c-semantics/semantics/c11/language/common/expr/additive.k)
Importing: Source(/path/to/c-semantics/semantics/c11/language/common/expr/assignment.k)
Importing: Source(/path/to/c-semantics/semantics/c11/language/common/expr/bitwise.k)
Importing: Source(/path/to/c-semantics/semantics/c11/language/common/expr/cast.k)
Importing: Source(/path/to/c-semantics/semantics/c11/language/common/expr/eval.k)
Importing: Source(/path/to/c-semantics/semantics/c11/language/common/expr/members.k)
Importing: Source(/path/to/c-semantics/semantics/c11/language/common/expr/multiplicative.k)
Importing: Source(/path/to/c-semantics/semantics/c11/language/common/expr/reference.k)
Importing: Source(/path/to/c-semantics/semantics/c11/language/common/expr/relational.k)
Importing: Source(/path/to/c-semantics/semantics/c11/language/common/expr/unary.k)
Importing: Source(/path/to/c-semantics/semantics/c11/language/common/memory/alloc.k)
Importing: Source(/path/to/c-semantics/semantics/c11/language/common/memory/reading.k)
Importing: Source(/path/to/c-semantics/semantics/c11/language/common/memory/writing.k)
Importing: Source(/path/to/c-semantics/semantics/c11/language/common/typing/common.k)
Importing: Source(/path/to/c-semantics/semantics/c11/language/common/typing/compatibility.k)
Importing: Source(/path/to/c-semantics/semantics/c11/language/common/typing/misc.k)
Importing: Source(/path/to/c-semantics/semantics/c11/language/common/typing/predicates.k)
Importing: Source(/path/to/c-semantics/x86-gcc-limited-libc/semantics/c-extensions-common.k)
Importing: Source(/path/to/c-semantics/x86-gcc-limited-libc/semantics/os-settings.k)
Importing: Source(/path/to/c-semantics/semantics/c11/library/init.k)
Importing: Source(/path/to/c-semantics/semantics/linking/linking.k)
Importing: Source(/path/to/c-semantics/semantics/common/common.k)
Importing: Source(/path/to/c-semantics/semantics/common/alignment.k)
Importing: Source(/path/to/c-semantics/semantics/common/bits.k)
Importing: Source(/path/to/c-semantics/semantics/common/builtin.k)
Importing: Source(/path/to/c-semantics/semantics/common/compat.k)
Importing: Source(/path/to/c-semantics/semantics/common/configuration.k)
Importing: Source(/path/to/c-semantics/semantics/common/error.k)
Importing: Source(/path/to/c-semantics/semantics/common/init.k)
Importing: Source(/path/to/c-semantics/semantics/common/memory.k)
Importing: Source(/path/to/c-semantics/semantics/common/resolution.k)
Importing: Source(/path/to/c-semantics/semantics/common/settings.k)
Importing: Source(/path/to/c-semantics/semantics/common/symloc.k)
Importing: Source(/path/to/c-semantics/semantics/common/syntax.k)
Importing: Source(/path/to/c-semantics/semantics/linking/error.k)
Importing: Source(/path/to/c-semantics/semantics/linking/init.k)
Importing: Source(/path/to/c-semantics/semantics/linking/resolution.k)
Importing: Source(/path/to/c-semantics/x86-gcc-limited-libc/semantics/c-settings.k)
org.kframework.utils.errorsystem.KEMException: [Warning] Compiler: missing entry for hook C_SEMANTICS.error
	at org.kframework.utils.errorsystem.KExceptionManager.registerInternal(KExceptionManager.java:188)
	at org.kframework.utils.errorsystem.KExceptionManager.register(KExceptionManager.java:175)
	at org.kframework.utils.errorsystem.KExceptionManager.registerCompilerWarning(KExceptionManager.java:109)
	at org.kframework.backend.ocaml.DefinitionToOcaml.definition(DefinitionToOcaml.java:1232)
	at org.kframework.backend.ocaml.OcamlBackend.accept(OcamlBackend.java:53)
	at org.kframework.kompile.KompileFrontEnd.run(KompileFrontEnd.java:71)
	at org.kframework.main.FrontEnd.main(FrontEnd.java:52)
	at org.kframework.main.Main.runApplication(Main.java:113)
	at org.kframework.main.Main.runApplication(Main.java:103)
	at org.kframework.main.Main.main(Main.java:52)
[Warning] Compiler: missing entry for hook C_SEMANTICS.error
```
I have seen the warning
```
[Warning] Compiler: missing entry for hook C_SEMANTICS.error
```
many times and it was never a problem.

**Comment by dwightguth** [comment]
Oh, I see. I turned on treating warnings as errors and unfortunately that's
incompatible with the open source version of the semantics. I'll fix this
on Monday, but in the meantime just remove the flag -w2e from
semantics/Makefile.
