### ISSUE TITLE
compilation errors

### ISSUE THREAD

**Issue by zhaomoy** [kframework/c-semantics#294]
My system is Ubuntu 16.04 and I followed the instructions here https://github.com/kframework/c-semantics/blob/master/INSTALL.md. However, I got the following errors:

/tmp/tmp-kompile-8672273625592264778.l:42634: warning, rule cannot be matched
/tmp/tmp-kompile-6594785130868115248.l:54701: warning, rule cannot be matched
/tmp/tmp-kompile-2524256743751109037.l:61862: warning, rule cannot be matched
org.kframework.utils.errorsystem.KEMException: [Error] Compiler: Had 1 parsing errors.
	at org.kframework.utils.errorsystem.KEMException.create(KEMException.java:113)
	at org.kframework.utils.errorsystem.KEMException.compilerError(KEMException.java:75)
	at org.kframework.kompile.DefinitionParsing.throwExceptionIfThereAreErrors(DefinitionParsing.java:164)
	at org.kframework.kompile.DefinitionParsing.saveCachesAndReportParsingErrors(DefinitionParsing.java:139)
	at org.kframework.kompile.DefinitionParsing.parseDefinitionAndResolveBubbles(DefinitionParsing.java:157)
	at org.kframework.kompile.Kompile.parseDefinition(Kompile.java:135)
	at org.kframework.kompile.Kompile.run(Kompile.java:121)
	at org.kframework.kompile.KompileFrontEnd.run(KompileFrontEnd.java:69)
	at org.kframework.main.FrontEnd.main(FrontEnd.java:52)
	at org.kframework.main.Main.runApplication(Main.java:113)
	at org.kframework.main.Main.runApplication(Main.java:103)
	at org.kframework.main.Main.main(Main.java:52)
[Error] Compiler: Had 1 parsing errors.
[Error] Inner Parser: Parse error: unexpected token ')'.
	Source(/work/kcc/c-semantics/x86-gcc-limited-libc/semantics/c-settings.k)
	Location(79,113,79,114)
Makefile:23: recipe for target 'x86-gcc-limited-libc/c11-translation-kompiled/c11-translation-kompiled/timestamp' failed
make[1]: *** [x86-gcc-limited-libc/c11-translation-kompiled/c11-translation-kompiled/timestamp] Error 113
make[1]: Leaving directory '/work/kcc/c-semantics/semantics'
Makefile:108: recipe for target 'translation-semantics' failed
make: *** [translation-semantics] Error 2
make: *** Waiting for unfinished jobs....
org.kframework.utils.errorsystem.KEMException: [Error] Compiler: Had 1 parsing errors.
	at org.kframework.utils.errorsystem.KEMException.create(KEMException.java:113)
	at org.kframework.utils.errorsystem.KEMException.compilerError(KEMException.java:75)
	at org.kframework.kompile.DefinitionParsing.throwExceptionIfThereAreErrors(DefinitionParsing.java:164)
	at org.kframework.kompile.DefinitionParsing.saveCachesAndReportParsingErrors(DefinitionParsing.java:139)
	at org.kframework.kompile.DefinitionParsing.parseDefinitionAndResolveBubbles(DefinitionParsing.java:157)
	at org.kframework.kompile.Kompile.parseDefinition(Kompile.java:135)
	at org.kframework.kompile.Kompile.run(Kompile.java:121)
	at org.kframework.kompile.KompileFrontEnd.run(KompileFrontEnd.java:69)
	at org.kframework.main.FrontEnd.main(FrontEnd.java:52)
	at org.kframework.main.Main.runApplication(Main.java:113)
	at org.kframework.main.Main.runApplication(Main.java:103)
	at org.kframework.main.Main.main(Main.java:52)
[Error] Compiler: Had 1 parsing errors.
[Error] Inner Parser: Parse error: unexpected token ')'.
	Source(/work/kcc/c-semantics/x86-gcc-limited-libc/semantics/c-settings.k)
	Location(79,113,79,114)
Makefile:27: recipe for target 'x86-gcc-limited-libc/cpp14-translation-kompiled/cpp14-translation-kompiled/timestamp' failed
make[1]: *** [x86-gcc-limited-libc/cpp14-translation-kompiled/cpp14-translation-kompiled/timestamp] Error 113
make[1]: Leaving directory '/work/kcc/c-semantics/semantics'
Makefile:114: recipe for target 'cpp-semantics' failed
make: *** [cpp-semantics] Error 2
org.kframework.utils.errorsystem.KEMException: [Error] Compiler: Had 1 parsing errors.
	at org.kframework.utils.errorsystem.KEMException.create(KEMException.java:113)
	at org.kframework.utils.errorsystem.KEMException.compilerError(KEMException.java:75)
	at org.kframework.kompile.DefinitionParsing.throwExceptionIfThereAreErrors(DefinitionParsing.java:164)
	at org.kframework.kompile.DefinitionParsing.saveCachesAndReportParsingErrors(DefinitionParsing.java:139)
	at org.kframework.kompile.DefinitionParsing.parseDefinitionAndResolveBubbles(DefinitionParsing.java:157)
	at org.kframework.kompile.Kompile.parseDefinition(Kompile.java:135)
	at org.kframework.kompile.Kompile.run(Kompile.java:121)
	at org.kframework.kompile.KompileFrontEnd.run(KompileFrontEnd.java:69)
	at org.kframework.main.FrontEnd.main(FrontEnd.java:52)
	at org.kframework.main.Main.runApplication(Main.java:113)
	at org.kframework.main.Main.runApplication(Main.java:103)
	at org.kframework.main.Main.main(Main.java:52)
[Error] Compiler: Had 1 parsing errors.
[Error] Inner Parser: Parse error: unexpected token ')'.
	Source(/work/kcc/c-semantics/x86-gcc-limited-libc/semantics/c-settings.k)
	Location(79,113,79,114)
Makefile:31: recipe for target 'x86-gcc-limited-libc/c11-cpp14-kompiled/c11-cpp14-kompiled/timestamp' failed
make[1]: *** [x86-gcc-limited-libc/c11-cpp14-kompiled/c11-cpp14-kompiled/timestamp] Error 113
make[1]: Leaving directory '/work/kcc/c-semantics/semantics'
Makefile:111: recipe for target 'execution-semantics' failed
make: *** [execution-semantics] Error 2

Thanks in advance.

**Comment by h0nzZik** [comment]
That is a bug. It is fixed in PR #290 .

**Comment by zhaomoy** [comment]
Thanks for your reply. I applied your patch but then got this error:

org.kframework.utils.errorsystem.KEMException: [Error] Critical: Error starting ocamlopt process: Source '/work/kcc/k/k-distribution/target/release/k/include/ocaml/marshalvalue.ml' does not exist (Source '/work/kcc/k/k-distribution/target/release/k/include/ocaml/marshalvalue.ml' does not exist)
	at org.kframework.utils.errorsystem.KEMException.create(KEMException.java:113)
	at org.kframework.utils.errorsystem.KEMException.criticalError(KEMException.java:34)
	at org.kframework.backend.ocaml.OcamlBackend.accept(OcamlBackend.java:138)
	at org.kframework.kompile.KompileFrontEnd.run(KompileFrontEnd.java:71)
	at org.kframework.main.FrontEnd.main(FrontEnd.java:52)
	at org.kframework.main.Main.runApplication(Main.java:113)
	at org.kframework.main.Main.runApplication(Main.java:103)
	at org.kframework.main.Main.main(Main.java:52)
Caused by: java.io.FileNotFoundException: Source '/work/kcc/k/k-distribution/target/release/k/include/ocaml/marshalvalue.ml' does not exist
	at org.apache.commons.io.FileUtils.copyFile(FileUtils.java:1074)
	at org.apache.commons.io.FileUtils.copyFile(FileUtils.java:1038)
	at org.kframework.backend.ocaml.OcamlBackend.accept(OcamlBackend.java:60)
	... 5 more
java.io.FileNotFoundException: Source '/work/kcc/k/k-distribution/target/release/k/include/ocaml/marshalvalue.ml' does not exist
	at org.apache.commons.io.FileUtils.copyFile(FileUtils.java:1074)
	at org.apache.commons.io.FileUtils.copyFile(FileUtils.java:1038)
	at org.kframework.backend.ocaml.OcamlBackend.accept(OcamlBackend.java:60)
	at org.kframework.kompile.KompileFrontEnd.run(KompileFrontEnd.java:71)
	at org.kframework.main.FrontEnd.main(FrontEnd.java:52)
	at org.kframework.main.Main.runApplication(Main.java:113)
	at org.kframework.main.Main.runApplication(Main.java:103)
	at org.kframework.main.Main.main(Main.java:52)

Did I miss something?

**Comment by ZhuXiaoran07** [comment]
Hi @h0nzZik , it seems I have compiled it successfully under your branch. But I came across an error when running the test:
`Unsupported option: /home/xiaoran/fix/c-semantics/dist/x86-gcc-limited-libc/lib/libc.so
`

**Comment by h0nzZik** [comment]
@zhaomoy have you tried to do clean build of runtimeverification/k ?

**Comment by zhaomoy** [comment]
@h0nzZik Thanks. You are right. 

However, after I did a clean build but the "test-build" target failed.

Translating the C standard library... (/work/kcc/c-semantics/x86-gcc-limited-libc)
cd /work/kcc/c-semantics/x86-gcc-limited-libc/src && /work/kcc/c-semantics/dist/kcc -nodefaultlibs -Xbuiltins -fno-native-compilation -shared -o /work/kcc/c-semantics/dist/x86-gcc-limited-libc/lib/libc.so *.c  -I .
Translating the C++ standard library... (/work/kcc/c-semantics/x86-gcc-limited-libc)
cd /work/kcc/c-semantics/x86-gcc-limited-libc/compiler-src && /work/kcc/c-semantics/dist/kcc -nodefaultlibs -Xbuiltins -fno-native-compilation -shared -o /work/kcc/c-semantics/dist/x86-gcc-limited-libc/lib/libstdc++.so *.C  -I .
Can't exec "rv-ifdefclear": No such file or directory at /work/kcc/c-semantics/dist/kcc line 4002.
Can't exec "rv-ifdefclear": No such file or directory at /work/kcc/c-semantics/dist/kcc line 4002.
Can't exec "merge-kcc-obj": No such file or directory at /work/kcc/c-semantics/dist/kcc line 3842.
Can't exec "merge-kcc-obj": No such file or directory at /work/kcc/c-semantics/dist/kcc line 3842.
Can't exec "rv-ifdefclear": No such file or directory at /work/kcc/c-semantics/dist/kcc line 4002.
tmp-kcc-tdrMBlt: file not recognized: File truncated
Can't exec "merge-kcc-obj": No such file or directory at /work/kcc/c-semantics/dist/kcc line 3501.
Done.
Can't exec "merge-kcc-obj": No such file or directory at /work/kcc/c-semantics/dist/kcc line 3842.
Can't exec "rv-ifdefclear": No such file or directory at /work/kcc/c-semantics/dist/kcc line 4002.
Can't exec "merge-kcc-obj": No such file or directory at /work/kcc/c-semantics/dist/kcc line 3842.
Can't exec "rv-ifdefclear": No such file or directory at /work/kcc/c-semantics/dist/kcc line 4002.
Can't exec "merge-kcc-obj": No such file or directory at /work/kcc/c-semantics/dist/kcc line 3842.
Can't exec "rv-ifdefclear": No such file or directory at /work/kcc/c-semantics/dist/kcc line 4002.
Can't exec "merge-kcc-obj": No such file or directory at /work/kcc/c-semantics/dist/kcc line 3842.
tmp-kcc-DCvJ8np: file not recognized: File truncated
Can't exec "merge-kcc-obj": No such file or directory at /work/kcc/c-semantics/dist/kcc line 3501.
Done.
Save to disk                                                 = 636551
Cleanup                                                      =   137
Total                                                        = 1075986
[Warning] Compiler: missing entry for hook C_SEMANTICS.error
[Warning] Compiler: missing entry for hook C_SEMANTICS.freeNativeObject
[Warning] Compiler: missing entry for hook C_SEMANTICS.nativeCall
[Warning] Compiler: missing entry for hook C_SEMANTICS.nativeFunctions
[Warning] Compiler: missing entry for hook C_SEMANTICS.printStackTrace
[Warning] Compiler: missing entry for hook C_SEMANTICS.readNativeByte
[Warning] Compiler: missing entry for hook C_SEMANTICS.writeNativeByte
make[1]: Leaving directory '/work/kcc/c-semantics/semantics'
Testing kcc...
printf "#include <stdio.h>\nint main(void) {printf(\"x\"); return 42;}\n" | dist/kcc -x c - -o dist/testProgram.compiled
Unsupported option: /work/kcc/c-semantics/dist/x86-gcc-limited-libc/lib/libc.so
Makefile:88: recipe for target 'test-build' failed
make: *** [test-build] Error 1

I noticed that you encountered a seemingly similar issue before (https://github.com/kframework/c-semantics/issues/264), although merge-kcc-obj wasn't part of the problem for you. Any idea what's the cause?

**Comment by dexter-qjq** [comment]
it just the error i met in #296 . you can try it.

**Comment by h0nzZik** [comment]
@zhaomoy Do you still have the problem, or something changed?
